### ISSUE TITLE
[opendataqna] [notebook 1] Issues found during setup 

### ISSUE THREAD

**Issue by ncvgl** [GoogleCloudPlatform/Open_Data_QnA#24]
**1_SetUpVectorStore.ipynb**
Missing a backtick in kgq_embeddings.py L35
Remove % sign in known_good_sql.csv
Do not say “no” to EXAMPLES - will lead to bugs in notebook 2

**Comment by orpzs** [comment]
- Backtick issue has been resolved as the line is commented anyway
- known good sql.csv is updated for v2-draft branch and will be moved to main branch soon
- EXAMPLES issue has been fixed on the v2-draft and will be merged to main soon
